# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Vishal Katariya"

author:
  twitter:          vkatariya8
  github:           vkatariya8
  email:            vkatariya8@gmail.com

copyright:
  year:             2017
  name:             Vishal Katariya

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "vkatariya8"

# URL
url:                "http://vishalkatariya.com" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "/" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Resume details
resume_avatar:                  "false"
resume_name:                    "Vishal Katariya"
resume_title:                   "PhD candidate"
resume_contact_email: "vkatariya8@gmail.com"
#resume_header_contact_info: "742 Evergreen Terrace, Springfield | 555-7334 | homerjsimpson@youremailaddress.com"
resume_header_intro: "<p>I'm a PhD candidate at Louisiana State University, doing research in quantum computing and quantum information theory.</p>"

resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false

resume_theme:                   default

# Navigation
nav:
  - katskable:           "Kat's Kable"
    url:            "/katskable"
- name:           "CV"
  url:            "/cv"
  # - name:           "Tags"
  #   url:            "/tags"
  # - name:           "Github"
  #   url:            "https://vishalkatariya.com"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]